---
- name: geoserver and css plugin
  hosts: all
  sudo: true

  handlers:

  - name: restart tomcat7
    service: name=tomcat7 state=restarted

  tasks:

  # http://geoserver.org/display/GEOS/Stable
  # http://docs.geoserver.org/stable/en/user/installation/linux/debian.html
  # http://docs.geoserver.org/latest/en/user/extensions/css/install.html

  - name: install tomcat7
    apt: pkg=tomcat7 state=present

  - set_fact: webapps_dir=/var/lib/tomcat7/webapps
  - set_fact: geoserver_version=2.4.2
  - set_fact: geoserver_zip=geoserver-{{ geoserver_version }}-war.zip
  - set_fact: geoserver_css_zip=geoserver-{{ geoserver_version }}-css-plugin.zip

  - name: fetch geoserver war
    get_url: url=http://sourceforge.net/projects/geoserver/files/GeoServer/{{ geoserver_version }}/{{ geoserver_zip }}
             dest={{ webapps_dir }}/{{ geoserver_zip }}
             sha256sum=36891856efa7c4a53cd39c2ab9379176c9d3fae8503d8b361686887eb8c3bc1d
    register: geoserver_zip_fetch

  - name: fetch geoserver css plugin
    get_url: url=http://aarnet.dl.sourceforge.net/project/geoserver/GeoServer%20Extensions/{{ geoserver_version }}/{{ geoserver_css_zip }}
             dest={{ webapps_dir }}/{{ geoserver_css_zip }}
             sha256sum=f9547d66dc187a32f46f6d9a7af12cd42a6666faed41f7baf71c786605f5f521
    register: geoserver_css_zip_fetch

  - name: stop tomcat if deploying app
    service: name=tomcat7 state=stopped
    when: geoserver_zip_fetch.changed or geoserver_css_zip_fetch.changed

  - name: delete existing app if deploying new one
    file: path={{ webapps_dir }}/{{ item }} state=absent
    with_items:
    - geoserver.war
    - geoserver
    when: geoserver_zip_fetch.changed or geoserver_css_zip_fetch.changed

  - name: extract geoserver war from downloaded zip
    command: unzip {{ geoserver_zip }} geoserver.war
             chdir={{ webapps_dir }}
             creates={{ webapps_dir }}/geoserver.war

  - name: extract geoserver app from geoserver war
    command: unzip geoserver.war -d geoserver
             chdir={{ webapps_dir }}
             creates={{ webapps_dir }}/geoserver
    notify: restart tomcat7

  - name: extract geoserver css plugin
    command: unzip {{ geoserver_css_zip }} -d geoserver/WEB-INF/lib
             chdir={{ webapps_dir }}
             creates={{ webapps_dir }}/geoserver/WEB-INF/lib/css-{{ geoserver_version }}.jar
    notify: restart tomcat7

