---
- name: opera browser
  hosts: all
  sudo: true
  tasks:

  # http://www.liberiangeek.net/2012/06/opera-12-released-how-to-install-it-in-ubuntu-12-04-precise-pangolin/

  - apt_key: url=http://deb.opera.com/archive.key id=30C18A2B
             keyring=/etc/apt/trusted.gpg.d/deb_opera_com.gpg

  - apt_repository: repo="deb http://deb.opera.com/opera/ stable non-free"
                    state=present update_cache=yes

  - apt: pkg=opera state=present

