---
- name: postgresql database for dev
  hosts: all
  sudo: true
  tasks:

  - apt: pkg={{ item }} state=present
    with_items:
    - postgresql
    - libpq-dev        # for ansible, and building pg clients generally
    - python-psycopg2  # for ansible

  - set_fact: normal_user={{ lookup('env','USER') }}
    sudo: false
  - set_fact: normal_user_home={{ lookup('env','HOME') }}
    sudo: false

  - name: create postgresql role for normal user
    shell: sudo -u postgres createuser --superuser --echo {{ normal_user }} &&
           touch {{ normal_user_home }}/.postgresql_role_created
           creates={{ normal_user_home }}/.postgresql_role_created

  - name: create postgresql db for normal user
    shell: sudo -u postgres createdb --encoding=UTF8 --echo {{ normal_user }} &&
           touch {{ normal_user_home }}/.postgresql_db_created
           creates={{ normal_user_home }}/.postgresql_db_created

  - name: allow all local users to connect to the DB via IPv4 as any role
    lineinfile: dest=/etc/postgresql/9.1/main/pg_hba.conf
                regexp='host    all             all             127.0.0.1/32'
                  line='host    all             all             127.0.0.1/32            trust'
                state=present backup=yes
    notify: restart postgresql

  handlers:

  - name: restart postgresql
    service: name=postgresql state=restarted

