---
- name: install some basic packages
  hosts: all
  sudo: true
  tasks:

  - apt: pkg=$item state=present
    with_items:
    - git
    - stow
    - vim
    - tmux
    - gdebi # installs .deb files (like dpkg), with automatic dependency resolution (unlike dpkg)

