---
- name: install some basic packages
  hosts: all
  sudo: true
  tasks:

  - apt: pkg=$item state=present
    with_items:
    - build-essential
    - libssl-dev
    - git
    - stow
    - vim
    - curl
    - tmux
    - gdebi

