---
- name: install compton compositor to fix tearing issues
  hosts: all
  sudo: true
  tasks:

  # install compton to fix tearing:
  #   * http://duncanlock.net/blog/2013/06/07/how-to-switch-to-compton-for-beautiful-tear-free-compositing-in-xfce/

  # about tearing:
  #   * http://en.wikipedia.org/wiki/Screen_tearing
  #   * http://www.youtube.com/watch?v=ceX18O9pvLs

  # alternative ways to resolve the tearing issue:
  #   * install compiz

  - name: disable xfwm compositing for user
    lineinfile: dest=~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
                regexp='use_compositing'
                line='    <property name="use_compositing" type="bool" value="false"/>'
                state=present backup=yes
    sudo: false

  - name: add compton ppa
    apt_repository: repo="ppa:richardgv/compton" state=present update_cache=yes

  - name: install compton package
    apt: pkg=compton state=present

  - name: basic compton config for user, as example
    copy: src=compton/compton.conf dest=~/.config/compton.conf.example
    sudo: false

  - name: make sure .config and autostart dirs are present
    file: path=~/.config/autostart state=directory
    sudo: false

  - name: copy in basic compton config for user, if non exists
    shell: cp ~/.config/compton.conf.example ~/.config/compton.conf
           creates=~/.config/compton.conf
    sudo: false

  - name: autostart compton for user
    copy: src=compton/compton.desktop dest=~/.config/autostart/compton.desktop
    sudo: false

  - debug: msg="You'll have to log out and back in to activate compton compositor and fix tearing problem!"

