---
- name: postgis
  hosts: all
  sudo: true

  tasks:

  # http://postgis.net/install/

  - apt_repository: repo="deb http://ppa.launchpad.net/sharpie/for-science/ubuntu quantal main"
                    state=present update_cache=yes

  - apt_repository: repo="deb http://ppa.launchpad.net/sharpie/postgis-stable/ubuntu precise main"
                    state=present update_cache=yes

  - apt_repository: repo="deb http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu raring main"
                    state=present update_cache=yes

  - apt: pkg=postgresql-9.1-postgis2 state=present

  - name: place an sql file for creating a spatially-enabled tempalte database
    copy: src=postgis/create_template_postgis_utf8.sql
          dest=/var/lib/postgresql/create_template_postgis_utf8.sql
    register: template_creation_script

  - name: create spatially-enabled template database, if the sql for that changed
    shell: psql -f /var/lib/postgresql/create_template_postgis_utf8.sql
    sudo_user: postgres
    when: template_creation_script.changed

