- name: vim dotfiles
  hosts: all
  tasks:

    - file: path=~/stow state=directory

    - git: repo=https://github.com/chrisberkhout/dot-vim.git dest=~/stow/dot-vim update=no
      register: dot_vim_clone
      
    - command: stow dot-vim chdir=~/stow
      when: dot_vim_clone.changed

    - name: switch to ssh URL (to be able to push without entering credentials)
      command: git remote set-url origin git@github.com:chrisberkhout/dot-vim.git chdir=~/stow/dot-vim
      when: dot_vim_clone.changed

