- name: other dotfiles
  hosts: all
  tasks:

    - file: path=~/stow state=directory

    - git: repo=https://github.com/chrisberkhout/dot-other.git dest=~/stow/dot-other update=no
      register: dot_other_clone
      
    - command: stow -v dot-other chdir=~/stow
      when: dot_other_clone.changed

    - name: switch to ssh URL (to be able to push without entering credentials)
      command: git remote set-url origin git@github.com:chrisberkhout/dot-other.git chdir=~/stow/dot-other
      when: dot_other_clone.changed

